### En este notebook se hace la exploración de la base datos de panorama TV infantil

In [2]:
import pandas as pd

# Cargar el archivo excel

df = pd.read_excel('OM - Base de datos panorama TV Infantil 2018 - 2019.xlsx')
df.head()

,Canal,Franja Horaria,Año,Fecha,Día de la semana,Mes,Share Niños 4-8 años,Rating en Miles Niños 4-8 años,Share Amas de casa 18+,Rating en Miles Amas de casa 18+,Share Personas 4+,Rating en Miles Personas 4+
0,Boomerang,0600-2400,2018,2018-01-01,Monday,1,1.66,4.39,0.42,5.18,0.71,23.11
1,Boomerang,0600-2400,2018,2018-01-02,Tuesday,1,3.67,11.86,0.52,6.99,1.21,44.42
2,Boomerang,0600-2400,2018,2018-01-03,Wednesday,1,2.44,7.54,0.33,4.78,0.84,31.47
3,Boomerang,0600-2400,2018,2018-01-04,Thursday,1,2.44,7.82,0.57,7.58,1.05,36.85
4,Boomerang,0600-2400,2018,2018-01-05,Friday,1,2.50,7.94,0.47,6.80,0.76,27.18

In [3]:
# ver el tamaño de dataset (filas, columnas)
df.shape

(13140, 12)

In [7]:
# Por cada columna, ver el tipo de dato y la cantidad de valores nulos
df.isnull().sum()

Canal                               0
Franja Horaria                      0
Año                                 0
Fecha                               0
Día de la semana                    0
Mes                                 0
Share Niños 4-8 años                0
Rating en Miles Niños 4-8 años      0
Share Amas de casa 18+              0
Rating en Miles Amas de casa 18+    0
Share Personas 4+                   0
Rating en Miles Personas 4+         0
dtype: int64

In [9]:
# por cada columna ver los valores únicos y su cantidad
for column in df.columns:
    print(f"Columna: {column}")
    print(df[column].value_counts())
    print("\n")

Columna: Canal
Canal
Boomerang            730
Cartoon Network      730
A&E                  730
Comedy Central       730
MTV                  730
Universal TV         730
TNT                  730
STAR Channel         730
Animal Planet        730
Discovery Channel    730
Nick Jr              730
Nickelodeon          730
NatGeo Kids          730
Disney Jr            730
Disney Channel       730
Disney XD            730
Discovery Kids       730
Señal Colombia       730
Name: count, dtype: int64


Columna: Franja Horaria
Franja Horaria
0600-2400    13140
Name: count, dtype: int64


Columna: Año
Año
2018    6570
2019    6570
Name: count, dtype: int64


Columna: Fecha
Fecha
2018-01-01    18
2019-04-25    18
2019-04-27    18
2019-04-28    18
2019-04-29    18
              ..
2018-09-03    18
2018-09-04    18
2018-09-05    18
2018-09-06    18
2019-12-31    18
Name: count, Length: 730, dtype: int64


Columna: Día de la semana
Día de la semana
Monday       1890
Tuesday      1890
Wednesday    1872
Thursday     1872
Friday       1872
Saturday     1872
Sunday       1872
Name: count, dtype: int64


Columna: Mes
Mes
1     1116
3     1116
5     1116
7     1116
8     1116
10    1116
12    1116
4     1080
6     1080
9     1080
11    1080
2     1008
Name: count, dtype: int64


Columna: Share Niños 4-8 años
Share Niños 4-8 años
0.00     755
0.01     541
0.02     317
0.03     187
0.04     185
        ...
8.67       1
14.67      1
13.43      1
12.53      1
9.29       1
Name: count, Length: 1229, dtype: int64


Columna: Rating en Miles Niños 4-8 años
Rating en Miles Niños 4-8 años
0.00     572
0.01     302
0.02     230
0.03     198
0.04     139
        ...
25.43      1
18.68      1
21.41      1
21.53      1
5.01       1
Name: count, Length: 2422, dtype: int64


Columna: Share Amas de casa 18+
Share Amas de casa 18+
0.17    198
0.07    196
0.05    191
0.14    188
0.09    187
       ...
2.99      1
3.45      1
2.88      1
2.98      1
2.85      1
Name: count, Length: 301, dtype: int64


Columna: Rating en Miles Amas de casa 18+
Rating en Miles Amas de casa 18+
1.00     26
2.48     23
0.74     22
2.52     22
0.67     21
         ..
19.39     1
14.28     1
12.77     1
18.61     1
15.99     1
Name: count, Length: 2421, dtype: int64


Columna: Share Personas 4+
Share Personas 4+
0.18    140
0.25    138
0.14    138
0.16    137
0.15    132
       ...
3.52      1
3.65      1
2.98      1
3.64      1
3.37      1
Name: count, Length: 357, dtype: int64


Columna: Rating en Miles Personas 4+
Rating en Miles Personas 4+
3.79     10
5.22     10
6.47      9
5.79      9
7.09      9
         ..
58.07     1
19.27     1
51.01     1
15.50     1
30.56     1
Name: count, Length: 6088, dtype: int64

In [10]:
# cargar el archivo excel como csv a la carpeta /src/data 

df.to_csv('src/data/panorama_tv_infantil.csv', index=False)

In [12]:
# Cargar diccionario con las descripciones

import json


column_descriptions = {
    "Canal": "Nombre del canal de televisión",
    "Franja Horaria": "Rango de horas de transmisión",
    "Año": "Año de la transmisión",
    "Fecha": "Fecha específica de la transmisión",
    "Día de la semana": "Día de la semana de la transmisión",
    "Mes": "Mes de la transmisión",
    "Share Niños 4-8 años": "Porcentaje de participación entre televidentes niños de 4-8 años",
    "Rating en Miles Niños 4-8 años": "Número en miles de niños de 4-8 años conectados al canal",
    "Share Amas de casa 18+": "Porcentaje de participación entre amas de casa de 18+ años",
    "Rating en Miles Amas de casa 18+": "Número en miles de amas de casa de 18+ años conectadas al canal",
    "Share Personas 4+": "Porcentaje de participación entre personas de 4+ años",
    "Rating en Miles Personas 4+": "Número en miles de personas de 4+ años conectadas al canal"
}

with open('src/data/diccionario_completo.json', 'w', encoding='utf-8') as f:
    json.dump(column_descriptions, f, indent=2, ensure_ascii=False)

# Agrupaciones por mes

In [19]:
# crear un df nuevo con las columnas agrupadas por promedio por mes para cada canal quitando las columnas de fecha, día de la semana y franja horaria

df_grouped = df.groupby(['Canal', 'Año', 'Mes']).agg({
    'Share Niños 4-8 años': 'mean',
    'Rating en Miles Niños 4-8 años': 'sum',
    'Share Amas de casa 18+': 'mean',
    'Rating en Miles Amas de casa 18+': 'sum',
    'Share Personas 4+': 'mean',
    'Rating en Miles Personas 4+': 'sum'
}).reset_index()


df_grouped.head()

,Canal,Año,Mes,Share Niños 4-8 años,Rating en Miles Niños 4-8 años,Share Amas de casa 18+,Rating en Miles Amas de casa 18+,Share Personas 4+,Rating en Miles Personas 4+
0,A&E,2018,1,0.080323,7.58,0.244516,105.31,0.195161,222.13
1,A&E,2018,2,0.084643,5.64,0.174286,68.72,0.153571,154.34
2,A&E,2018,3,0.153226,14.38,0.176129,76.31,0.176452,198.28
3,A&E,2018,4,0.031667,2.59,0.170667,73.12,0.140333,150.86
4,A&E,2018,5,0.049032,4.05,0.127419,56.46,0.129355,144.47

In [ ]:
# subir csv a la carpeta /src/data

df_grouped.to_csv('src/data/panorama_tv_infantil_agrupado_mes.csv', index=False)